### ISSUE TITLE
how can I run the code of Tutorials and Examples

### ISSUE THREAD

**Issue by scut-salmon** [hydrogo/rainymotion#1]
Hi,
I have read the Tutorials of this package, and found the example code here
https://rainymotion.readthedocs.io/en/latest/notebooks/nowcasting.html

but I can not found the data needed for the code, how can I get them? 

Thanks,
Zhang

**Comment by hydrogo** [comment]
Dear Zhang,

Thank you for your interest in `rainymotion.`
In case you follow our installation instructions (https://rainymotion.readthedocs.io/en/latest/gettingstarted.html), you had to download all you need (including data) by cloning our main repo (https://github.com/hydrogo/rainymotion).
If you are interested only in data, you can download it directly from the rainymotion data folder (https://github.com/hydrogo/rainymotion/blob/master/data/data.h5). You can also find the RY data only on the DWD open data portal (https://opendata.dwd.de/weather/radar/radolan/ry/).

Best,
Georgy

**Comment by scut-salmon** [comment]
Thanks for your answer, you are right.
