### ISSUE TITLE
Possible error in _interpolator()

### ISSUE THREAD

**Issue by Yuchaowni** [hydrogo/rainymotion#12]
I think there is an error in the _interpolator() function of models.py:

at line 606:

def _interpolator(points, coord_source, coord_target, method="idw"):
    coord_source_i, coord_source_j = coord_source
    coord_target_i, coord_target_j = coord_target
    # reshape
    trg = np.vstack((coord_source_i.ravel(), coord_source_j.ravel())).T
    src = np.vstack((coord_target_i.ravel(), coord_target_j.ravel())).T
I think trg and src should exchange their positions.

**Comment by hydrogo** [comment]
Hi @Yuchaowni,
it's not the bug, it's a feature.

There are different concepts of what to consider as sources and targets during the interpolation routine.

In _interpolator() function or target is to interpolate advected values of rain pixels back to grid cells (which are source coordinates in advection's module).

But you pointed out an important issue of code readability -- I will consider it in the next release.

Thanks for using `rainymotion`!

Best,
Georgy

**Comment by Yuchaowni** [comment]
Hi Georgy, 
Thank for the explanation! This solves my confusion. 

Best,
Yuchao
