### ISSUE TITLE
Questions on RYScaler()

### ISSUE THREAD

**Issue by Yuchaowni** [hydrogo/rainymotion#13]
Hi Georgy, 
I have 2 questions about the function utils.RYScaler():

1. For input data of cv2.calcOpticalFlowPyrLK() or cv2.optflow.createOptFlow_DIS(), 
  why don't you directly use rain rate (mm/h) scaled to [0,256]?  If use dbz, I suspect the intensity conservation assumption will be less obeyed than linear rain rate.  

2. inv_RYScaler() has converted data back to mm/5 min. But when doing metrics such as CSI, the threshold is set using the unit of mm/h.  I guess there is an issue here. 

Thanks. 
Yuchao

**Comment by hydrogo** [comment]
Hi Yuchao,

1. Our preliminary work shows that the provided scaling strategy is more beneficial than linear scaling to [0, 255]. In your workflow, you can use any scaler you think fits your needs the best.

2. You are right, before metrics calculation, you should convert depth back to intensity. There is utils.depth2intensity() method for this purpose.

Best regards,
Georgy

**Comment by Yuchaowni** [comment]
Thank you, Georgy.  I have tested 25 k cases of my own data and have found log scale is consistently 1%-3% better than linear scale in terms of threat score. 

I really appreciated your providing such a great open-source library. 

Best regards,
Yuchao

**Comment by hydrogo** [comment]
Dear Yuchao,
thank you for your interest in `rainymotion`!

You may also check scaling procedures suggested in the paper by Woo and Wong (2017) -- could be a reliable option for your study if you are mainly focusing on intense precipitation.

Cheers,
Georgy

Woo, W.-C.; Wong, W.-K. Operational Application of Optical Flow Techniques to Radar-Based Rainfall Nowcasting. Atmosphere 2017, 8, 48. https://doi.org/10.3390/atmos8030048
