### ISSUE TITLE
Questions about  converting rainfall to radar reflectivity factor

### ISSUE THREAD

**Issue by YvZheng** [hydrogo/rainymotion#14]
It is an excellent library for radar nowcasting, but i have some questions about converting rainfall to radar reflectivity factor in your functions, why should convert rainfall to radar reflectivity factor?

**Comment by hydrogo** [comment]
Hi @YvZheng,
Thank you for your interest in `rainymotion`!

Core functions for optical flow calculation require input data being int8 type. There are plenty of ways of how to convert radar rainfall input data, which may be in mm, mm/h, dB, etc, to int8 (greyscale). More importantly, the selected transformation will affect the final distribution of values, and consequently, the performance of optical flow methods (which are based on pixel-wise comparison of greyscale "brightness"). This way, it is important to choose a particular transformation for a particular task. For example, Woo and Wong (2017) proposed to use the inverse tangent function (communicated before by Cheung and Yeung (2012)) for the transformation of reflectivity to greyscale to put more focus to extreme values.

Therefore, our `RY_Scaler` was investigated to fit our needs the best. You can try to use MinMax scaler from, e.g., `scikit-learn` library, or develop your own scaler in case `RY_scaler` doesn't fit your purpose.

Sorry for the late response and best regards,
Georgy

Cheung, P., & Yeung, H. Y. (2012, August). Application of optical-flow technique to significant convection nowcast for terminal areas in Hong Kong. In The 3rd WMO International Symposium on Nowcasting and Very Short-Range Forecasting (WSN12) (pp. 6-10).
Woo, W.-C.; Wong, W.-K. Operational Application of Optical Flow Techniques to Radar-Based Rainfall Nowcasting. Atmosphere 2017, 8, 48.

**Comment by YvZheng** [comment]
thanks for your response.
