### ISSUE TITLE
How to run the model?

### ISSUE THREAD

**Issue by Omike95** [hydrogo/rainymotion#16]
I have this error each time i tried running the model 
I followed all the instructions 
>>> model.input_data = np.load("C:/Users/Administrator/hydrogo/data/data.h5")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'np' is not defined
>>>

**Comment by hydrogo** [comment]
Hi @Omike95 ,
It seems that you did not import numpy library. Anyway, I recommend using h5py library for loading HDF (.h5) files than numpy.
Also, I recommend you to follow the instructions from the very beginning, i.e., installation of an anaconda environment.
Good luck!
