### ISSUE TITLE
Relevance of files along with data.h5.

### ISSUE THREAD

**Issue by BinoyKadakkal** [hydrogo/rainymotion#17]
![rainymotion](https://user-images.githubusercontent.com/108899419/183063512-db190e0e-e40f-4e25-972d-54cf8cc9bfea.png)

Sir, could you please explain the relevance of files along with data.h5.The screenshot of the same is attached herewith. For my study I have only single file in NetCDF format. Can I proceed with this single file?

**Comment by hydrogo** [comment]
Dear @BinoyKadakkal,
you can check our real case verification scenario (https://rainymotion.readthedocs.io/en/latest/notebooks/nowcasting.html) to look at the mentioned data's utilization.
