### ISSUE TITLE
terminate called after throwing an instance of 'std::length_error'

### ISSUE THREAD

**Issue by BinoyKadakkal** [hydrogo/rainymotion#18]
I tried to run the four models, but shows some error.
I used the following code,

import numpy as np
import matplotlib.pyplot as plt
from rainymotion.models import DenseRotation

# initialize the model
model = DenseRotation()

# upload data to the model instance
model.input_data = np.load("/home/binoy/binoy/data.npy",allow_pickle=True)

# run the model with default parameters
nowcast = model.run()
print (nowcast)

While running Dense and DenseRotation it shows that,
![dense and denserotation](https://user-images.githubusercontent.com/108899419/185602671-a6e0a21b-6bac-4ce6-b8dd-0be87cd68637.png)

in Sparse it seen that,
![Sparse](https://user-images.githubusercontent.com/108899419/185602736-5a3a0f37-8113-4b33-876b-27cb7c51db98.png)

for SparseSD,
![sparseSD](https://user-images.githubusercontent.com/108899419/185603599-1956e149-a8a6-479f-bf7b-ca43fd21a2b2.png)

I don't have a strong base in python. So got stuck in running process, please help me to resolve the same. 
Thanks in advance!!!!!!

**Comment by hydrogo** [comment]
Hey @BinoyKadakkal,
could you upload your data and share the link here? I will have a closer look next week. Thanks!

**Comment by BinoyKadakkal** [comment]
Sir,
I had used the sample data provided by converting it into numpy.

**Comment by BinoyKadakkal** [comment]
Sir,
I had used the sample data provided with rainymotion. Before applying to the model i had converted it in to numpy.

**Comment by hydrogo** [comment]
Dear @BinoyKadakkal,
you can find a working example of the utilization of provided data and rainymotion models in our documentation, section "Real case verification: the Braunsbach event" (https://rainymotion.readthedocs.io/en/latest/notebooks/nowcasting.html): from reading data to plotting the obtained verification metrics. I hope it will help you. Good luck!

**Comment by BinoyKadakkal** [comment]
Hi sir
Could you please share a sample dataset in the numpy format.

Thanks in advance.

**Comment by hydrogo** [comment]
In the example above, when we implement nowcasting models in the optical_flow() function, there is a step for reading input data, i.e.:
inputs = np.array([ data_instance[key][()] for key in eval_instance[key][0] ])
where data_instance is "data = h5py.File("../../data/data.h5", mode="r")" (the second cell), and eval_instance is "eval_idx = np.load("../../data/eval_dict.npy").item()" (the second cell)

to unpack data in numpy array format, just browse data.keys() to find out the structure of the provided dataset.

**Comment by BinoyKadakkal** [comment]
Thank you Sir
Its working fine with sample data provided.
