### ISSUE TITLE
Wrong shape numpy array in new coordinates of Dense and DenseRotation

### ISSUE THREAD

**Issue by RubenImhoff** [hydrogo/rainymotion#3]
Hi all,

Thanks for the great RainyMotion initiative, it's great to have a nowcasting 'benchmark' as open-source code. 
I have tried the code on the Dutch KNMI radar data (similar to Radolan, but with 765 rows and 700 cols - hence, not a nice square). The Sparse and SparseSD codes work smoothly, but with both Dense algorithms, I get the following error: 
`ValueError: operands could not be broadcast together with shapes (700,765) (765,700)`

Looking a bit further into the code, I found the following (example of Dense @ line 527, but similar in DenseRotation):
`        # no need in rounding deltas 
        delta_x = delta[::, ::, 0]
        delta_y = delta[::, ::, 1]
        
        # make a source meshgrid
        coord_source_i, coord_source_j = np.meshgrid(range(last_frame.shape[0]), range(last_frame.shape[1]))
        
        # propagate our image through time based on dense flow
        # container for our nowcasts
        nowcst_frames = []
        
        for lead_step in range(self.lead_steps):       
            
            # calculate new coordinates of radar pixels
            coord_target_i = coord_source_i + delta_x * (lead_step + 1)
            coord_target_j = coord_source_j + delta_y * (lead_step + 1)`

coord_source_i is a 2D-array with 700 rows and 765 columns, but delta_x is a 2D-array with 765 rows and 700 columns. Hence, that raises the error.  
The same problem seems to occur with coord_source_j.

Since I was not totally sure what the array should look like, I can't come up with a solution yet. Though, it seems like something goes wrong with the constructing of the meshgrid? 

Thanks for your help!

Kind regards,

Ruben Imhoff

**Comment by hydrogo** [comment]
Hi Ruben,

thanks a lot for pointing this issue out -- I have already fixed it in the next version of `rainymotion`, but still didn't release it because of the high load caused by responding to referee's comments (https://www.geosci-model-dev-discuss.net/gmd-2018-166/#discussion).

As the fastest solution, I can propose to change the order of arrays used for meshgrid computation
from
```
coord_source_i, coord_source_j = np.meshgrid(range(last_frame.shape[0]), range(last_frame.shape[1]))
```
to
```
coord_source_i, coord_source_j = np.meshgrid(range(last_frame.shape[1]), range(last_frame.shape[0]))
```

All the best,
Georgy

**Comment by RubenImhoff** [comment]
Hi Georgy,

Thanks for your quick response and that during Christmas (Merry Christmas!). 

Ah perfect, that should fix it! Good luck with the changes to the manuscript - I've read the GMD discussion article, nice work - and I'm looking forward to the next release of RainyMotion.


Cheers,

Ruben

**Comment by hydrogo** [comment]
Dear Ruben,

Thanks a lot for your feedback! We estimate the next release date at the late January, and there will be massive improvements:
1. x20 speed-up
2. better performance for longer lead times
3. options for producing nowcasts in an ensemble mode.

Cheers,
Georgy

P.S. It is weird, but we Russians have Christmas two weeks later :-) But thanks anyway and Merry Christmas!

**Comment by RubenImhoff** [comment]
Hi Georgy,

That sounds very good, useful improvements! 
Oh, I didn't know that! Thanks though! :) 


Cheers,

Ruben
