### ISSUE TITLE
Sparse model crashing at certain input

### ISSUE THREAD

**Issue by elekt** [hydrogo/rainymotion#6]
Hey Gerogy,

Awesome and clean project! I am using rainymotion in my MSc thesis about weather nowcasting for intraday electricity trading. It works pretty neat for benchmarking optical flow methods.
My issue is that the Sparse model crashes on certain input.  

Minimum example code:
```
import glob

import numpy
from PIL import Image
from rainymotion.models import Sparse

imageFolderPath = f'/PATH/TO/failing_data'
imagePath = sorted(glob.glob(imageFolderPath + '/*.png'))

im_array = numpy.array([numpy.array(Image.open(img).convert('L'), 'f') for img in imagePath])
model = Sparse()

model.input_data = im_array
nowcasts = model.run()
```
[failing_data.zip](https://github.com/hydrogo/rainymotion/files/3097890/failing_data.zip)

My investigations went until `_sparse_linear` in models.py, 
```
new_corners, st, err = cv2.calcOpticalFlowPyrLK(prevImg=data_instance[i - 1],
                                                nextImg=data_instance[i],
                                                prevPts=old_corners,
                                                nextPts=None,
                                                **of_params['lk_pars'])
```
This method call returned all None-s and causing crashing 1 line after. 
All output:

```
/home/user/anaconda3/envs/rainymotion/lib/python3.7/site-packages/wradlib/io/xarray.py:951: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  class XRadVol(collections.MutableMapping):
Traceback (most recent call last):
  File "/home/user/Workspace/Dexter/task-pod-ml/nowcasting/src/optical_flow_sparse_error_minimal.py", line 15, in <module>
    nowcasts = model.run()
  File "/home/user/anaconda3/envs/rainymotion/lib/python3.7/site-packages/rainymotion-0.1-py3.7.egg/rainymotion/models.py", line 256, in run
  File "/home/user/anaconda3/envs/rainymotion/lib/python3.7/site-packages/rainymotion-0.1-py3.7.egg/rainymotion/models.py", line 60, in _sparse_linear
AttributeError: 'NoneType' object has no attribute 'ravel'
```

I have similar inputs like this, but they do not crash all the time just with certain sets. All other models work fine with the same data.

**Comment by hydrogo** [comment]
Hi Elekes,
sorry for the late response -- there are Easter holidays in Germany from Friday until today. 

Thanks for reporting, I will try to check your issue tomorrow when coming back to my work :-/

Best,
Georgy

**Comment by hydrogo** [comment]
Hi Elekes,
The problem you described relates to data preprocessing routine. As 'rainymotion' was developed primarily as a tool for rainfall nowcasting, it has two built-in methods for data conversion from _rainfall depth_ or _reflectivity_ to 'uint8' type (0-255 integers) to be compatible with computer vision algorithms provided by `opencv` and `scikit-image` libraries -- namely, **.scaler** and **.inverse_scaler** as methods in Sparse() model class. 

So, it is important to explicitly assign these methods to the new scalers if you are dealing with different data from RY product of DWD.

As a solution, I propose:
```
import glob

import numpy
from PIL import Image
from rainymotion.models import Sparse

# I have modified data reading process a bit
#imageFolderPath = f'/PATH/TO/failing_data'
#imagePath = sorted(glob.glob(imageFolderPath + '/*.png'))
imagePath = [f'failing_data/{i}.png' for i in range(24)]

im_array = numpy.array([numpy.array(Image.open(img).convert('L'), 'f') for img in imagePath])

# Put new scalers here
# So we just need to convert 'float32' to 'uint8' for **scaler** and fo nothing for **inverse_scaler**
def PNG_Scaler(X):
    return X.astype("uint8"), None, None

def PNG_inv_Scaler(X, c1, c2):
    return X.astype("uint8")

# create model instance and assign our data and functions
model = Sparse()
model.input_data = im_array
model.scaler = PNG_Scaler
model.inverse_scaler = PNG_inv_Scaler

# now it works
nowcasts = model.run()
```

By the way, I do not recommend you to use the **Sparse** group of models. For better performance try to use the **Dense** group.

Thank you for reporting the problem -- in the next version of `rainymotion` I will try to make a module for automatic inference of input data type to avoid most of I/O problems users have at the moment.

**Comment by elekt** [comment]
Thanks a lot, it does help with the issue, however still not for everything.
I have similar satellite imagery, same sized images, 11 different spectral bands. The size and data type (numpy.float32) is the same every case. 

```
Traceback (most recent call last):
  File "/home/user/.pycharm_helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/home/user/.pycharm_helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/user/.pycharm_helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/user/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/user/tmp/pycharm_project_666/nowcasting/src/optical_flow.py", line 126, in <module>
    nowcasts = model.run()
  File "/home/user/anaconda3/envs/rainymotion/lib/python3.7/site-packages/rainymotion-0.1-py3.7.egg/rainymotion/models.py", line 396, in run
  File "/home/user/anaconda3/envs/rainymotion/lib/python3.7/site-packages/rainymotion-0.1-py3.7.egg/rainymotion/models.py", line 133, in _sparse_sd
cv2.error: OpenCV(3.4.4) ../modules/video/src/lkpyramid.cpp:1231: error: (-215:Assertion failed) (npoints = prevPtsMat.checkVector(2, CV_32F, true)) >= 0 in function 'calc'
```

And an other, by returning again None in models.py:36.
```
old_corners = cv2.goodFeaturesToTrack(data_instance[0], mask = None, **of_params['st_pars'])
```

I found the reason - like which spectral band causing the error - but I don't see a difference from the data storing standpoint. If I find the solution I report it here, or if I can't this week and you have capacity I'll make a more clear description again.

**Comment by hydrogo** [comment]
At the moment there is no direct way to use `rainymotion` for images with more than one channel. We will fix it in the next version.

**Comment by elekt** [comment]
Converting beforehand the files from RGB to 1 channel grayscale did the trick!
Thanks
