### ISSUE TITLE
Reduce line length to improve code readability

### ISSUE THREAD

**Issue by fionaRust** [hydrogo/rainymotion#7]
Hi Georgy,

Have you considered making your code pep8 compliant? You can use a tool like pycodestyle (https://pypi.org/project/pycodestyle/) to show you were you aren't compliant. I think it would make your code a lot more readable, especially the docstrings. At the moment it is hard to read your docstrings in the models.py file.

Thanks

Fiona

**Comment by hydrogo** [comment]
Hi Fiona,

Thank you for raising this issue.

I will follow pep8 requirements preparing the next `rainymotion` release (late 2019).

Cheers,
Georgy

**Comment by hydrogo** [comment]
Hi Fiona,
thanks to @ElmerJeanpierreLopez the `rainymotion` code has been mainly adapted to follow PEP8.
Best regards,
Georgy
