### ISSUE TITLE
How I can use GPU with rainymotion?

### ISSUE THREAD

**Issue by martinht7** [hydrogo/rainymotion#8]
Hi, 

I have a large amount of data right now, and I wonder if there is a way that I can train the rainymotion model with GPU...

**Comment by hydrogo** [comment]
Hi there,
Our `rainymotion` models work out of the box without any training -- there are only some parameters of optical flow calculation and advection scheme you can adjust by hand or using more complex optimization routines (i.e., differential evolution). At the moment, `rainymotion` models run pretty fast on CPU, but we do not consider developing the support for computation on GPU.

Our group is also currently working on [`rainnet`](https://www.ecmwf.int/sites/default/files/elibrary/2018/18729-rainymotion-and-rainnet-optical-flow-and-deep-learning-models-radar-based-precipitation.pdf`) -- the deep neural network for precipitation nowcasting that can be trained from scratch on a new data. Unfortunately, we can not ready to share `rainnet` code and training routine until the submission of the corresponding paper. Thank you for your understanding.

Cheers,
Georgy
